# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\x0b\x63\x61lculadora\"#\n\x0bSomaRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"!\n\x0cSomaResponse\x12\x11\n\tresultado\x18\x01 \x01(\x01\x32M\n\x0b\x43\x61lculadora\x12>\n\x05Somar\x12\x18.calculadora.SomaRequest\x1a\x19.calculadora.SomaResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOMAREQUEST']._serialized_start=33
  _globals['_SOMAREQUEST']._serialized_end=68
  _globals['_SOMARESPONSE']._serialized_start=70
  _globals['_SOMARESPONSE']._serialized_end=103
  _globals['_CALCULADORA']._serialized_start=105
  _globals['_CALCULADORA']._serialized_end=182
# @@protoc_insertion_point(module_scope)
